package MuxixApp;


/**
* MuxixApp/doublen1Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Muxix.idl
* Sunday, 4 February, 2018 9:15:04 PM IST
*/

public final class doublen1Holder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public doublen1Holder ()
  {
  }

  public doublen1Holder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MuxixApp.doublen1Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MuxixApp.doublen1Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MuxixApp.doublen1Helper.type ();
  }

}
