package MuxixApp;


/**
* MuxixApp/doubleshowHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Muxix.idl
* Sunday, 4 February, 2018 9:15:04 PM IST
*/

public final class doubleshowHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public doubleshowHolder ()
  {
  }

  public doubleshowHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MuxixApp.doubleshowHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MuxixApp.doubleshowHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MuxixApp.doubleshowHelper.type ();
  }

}
