package MuxixApp;


/**
* MuxixApp/MuxixHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Muxix.idl
* Sunday, 4 February, 2018 9:15:05 PM IST
*/

abstract public class MuxixHelper
{
  private static String  _id = "IDL:MuxixApp/Muxix:1.0";

  public static void insert (org.omg.CORBA.Any a, MuxixApp.Muxix that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MuxixApp.Muxix extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MuxixApp.MuxixHelper.id (), "Muxix");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MuxixApp.Muxix read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MuxixStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MuxixApp.Muxix value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MuxixApp.Muxix narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MuxixApp.Muxix)
      return (MuxixApp.Muxix)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MuxixApp._MuxixStub stub = new MuxixApp._MuxixStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MuxixApp.Muxix unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MuxixApp.Muxix)
      return (MuxixApp.Muxix)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MuxixApp._MuxixStub stub = new MuxixApp._MuxixStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
