package MuxixApp;


/**
* MuxixApp/MuxixPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Muxix.idl
* Sunday, 4 February, 2018 9:15:05 PM IST
*/

public abstract class MuxixPOA extends org.omg.PortableServer.Servant
 implements MuxixApp.MuxixOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("show", new java.lang.Integer (0));
    _methods.put ("getPrice", new java.lang.Integer (1));
    _methods.put ("getItems", new java.lang.Integer (2));
    _methods.put ("Borrow", new java.lang.Integer (3));
    _methods.put ("ReturnMusic", new java.lang.Integer (4));
    _methods.put ("orderDetails", new java.lang.Integer (5));
    _methods.put ("getArtist", new java.lang.Integer (6));
    _methods.put ("getAlbum", new java.lang.Integer (7));
    _methods.put ("getCompany", new java.lang.Integer (8));
    _methods.put ("getSongs", new java.lang.Integer (9));
    _methods.put ("shutdown", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MuxixApp/Muxix/show
       {
         double $result[] = null;
         $result = this.show ();
         out = $rh.createReply();
         MuxixApp.doubleshowHelper.write (out, $result);
         break;
       }

       case 1:  // MuxixApp/Muxix/getPrice
       {
         double $result[] = null;
         $result = this.getPrice ();
         out = $rh.createReply();
         MuxixApp.doublepriceHelper.write (out, $result);
         break;
       }

       case 2:  // MuxixApp/Muxix/getItems
       {
         double $result[] = null;
         $result = this.getItems ();
         out = $rh.createReply();
         MuxixApp.doubleitemHelper.write (out, $result);
         break;
       }

       case 3:  // MuxixApp/Muxix/Borrow
       {
         double choice = in.read_double ();
         double remaining[] = MuxixApp.doubleremHelper.read (in);
         String $result = null;
         $result = this.Borrow (choice, remaining);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // MuxixApp/Muxix/ReturnMusic
       {
         double c1 = in.read_double ();
         double n1[] = MuxixApp.doublen1Helper.read (in);
         double qty1[] = MuxixApp.doubleqty1Helper.read (in);
         String $result = null;
         $result = this.ReturnMusic (c1, n1, qty1);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // MuxixApp/Muxix/orderDetails
       {
         String $result[] = null;
         $result = this.orderDetails ();
         out = $rh.createReply();
         MuxixApp.stringorderHelper.write (out, $result);
         break;
       }

       case 6:  // MuxixApp/Muxix/getArtist
       {
         String $result[] = null;
         $result = this.getArtist ();
         out = $rh.createReply();
         MuxixApp.stringartistHelper.write (out, $result);
         break;
       }

       case 7:  // MuxixApp/Muxix/getAlbum
       {
         String $result[] = null;
         $result = this.getAlbum ();
         out = $rh.createReply();
         MuxixApp.stringalbumHelper.write (out, $result);
         break;
       }

       case 8:  // MuxixApp/Muxix/getCompany
       {
         String $result[] = null;
         $result = this.getCompany ();
         out = $rh.createReply();
         MuxixApp.stringcompanyHelper.write (out, $result);
         break;
       }

       case 9:  // MuxixApp/Muxix/getSongs
       {
         String $result[][] = null;
         $result = this.getSongs ();
         out = $rh.createReply();
         MuxixApp.stringsongsHelper.write (out, $result);
         break;
       }


  //public String[][] getSongs() throws RemoteException;
       case 10:  // MuxixApp/Muxix/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MuxixApp/Muxix:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Muxix _this() 
  {
    return MuxixHelper.narrow(
    super._this_object());
  }

  public Muxix _this(org.omg.CORBA.ORB orb) 
  {
    return MuxixHelper.narrow(
    super._this_object(orb));
  }


} // class MuxixPOA
