package MuxixApp;

/**
* MuxixApp/MuxixHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Muxix.idl
* Sunday, 4 February, 2018 9:15:05 PM IST
*/

public final class MuxixHolder implements org.omg.CORBA.portable.Streamable
{
  public MuxixApp.Muxix value = null;

  public MuxixHolder ()
  {
  }

  public MuxixHolder (MuxixApp.Muxix initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MuxixApp.MuxixHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MuxixApp.MuxixHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MuxixApp.MuxixHelper.type ();
  }

}
