package MuxixApp;


/**
* MuxixApp/Muxix.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Muxix.idl
* Sunday, 4 February, 2018 9:15:05 PM IST
*/

public interface Muxix extends MuxixOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Muxix
